INSERT INTO SELLERS (NAME, SALARY, BONUS, GENDER)
VALUES ('Eduardo Rodrigues', 12500, 100, 1);
INSERT INTO SELLERS (NAME, SALARY, BONUS, GENDER)
VALUES ('Eduardo Andre', 1500, 10, 1);
INSERT INTO SELLERS (NAME, SALARY, BONUS, GENDER)
VALUES ('Eduardo Marcos', 2500, 60, 1);
INSERT INTO SELLERS (NAME, SALARY, BONUS, GENDER)
VALUES ('Eduarda Maria', 50500, 32, 0);